import {
  Corner,
  Edge,
  MoveDefinition,
  FaceMove,
} from "@/lib/cubeTypes";

export const MOVES: Record<FaceMove, MoveDefinition> = {
  U: {
    corners: [
      Corner.UFL,
      Corner.ULB,
      Corner.UBR,
      Corner.URF,
      Corner.DFR,
      Corner.DLF,
      Corner.DBL,
      Corner.DRB,
    ],
    cornerOri: [0, 0, 0, 0, 0, 0, 0, 0],
    edges: [
      Edge.UF,
      Edge.UL,
      Edge.UB,
      Edge.UR,
      Edge.DR,
      Edge.DF,
      Edge.DL,
      Edge.DB,
      Edge.FR,
      Edge.FL,
      Edge.BL,
      Edge.BR,
    ],
    edgeOri: [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
  },

  D: {
    corners: [
      Corner.URF,
      Corner.UFL,
      Corner.ULB,
      Corner.UBR,
      Corner.DRB,
      Corner.DFR,
      Corner.DLF,
      Corner.DBL,
    ],
    cornerOri: [0, 0, 0, 0, 0, 0, 0, 0],
    edges: [
      Edge.UR,
      Edge.UF,
      Edge.UL,
      Edge.UB,
      Edge.DB,
      Edge.DR,
      Edge.DF,
      Edge.DL,
      Edge.FR,
      Edge.FL,
      Edge.BL,
      Edge.BR,
    ],
    edgeOri: [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
  },

  R: {
    corners: [
      Corner.DFR,
      Corner.UFL,
      Corner.ULB,
      Corner.URF,
      Corner.DRB,
      Corner.DLF,
      Corner.DBL,
      Corner.UBR,
    ],
    cornerOri: [2, 0, 0, 1, 1, 0, 0, 2],
    edges: [
      Edge.FR,
      Edge.UF,
      Edge.UL,
      Edge.UB,
      Edge.BR,
      Edge.DF,
      Edge.DL,
      Edge.DB,
      Edge.DR,
      Edge.FL,
      Edge.BL,
      Edge.UR,
    ],
    edgeOri: [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
  },

  L: {
    corners: [
      Corner.URF,
      Corner.ULB,
      Corner.DBL,
      Corner.UBR,
      Corner.DFR,
      Corner.UFL,
      Corner.DLF,
      Corner.DRB,
    ],
    cornerOri: [0, 1, 2, 0, 0, 2, 1, 0],
    edges: [
      Edge.UR,
      Edge.UF,
      Edge.BL,
      Edge.UB,
      Edge.DR,
      Edge.DF,
      Edge.FL,
      Edge.DB,
      Edge.FR,
      Edge.UL,
      Edge.DL,
      Edge.BR,
    ],
    edgeOri: [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
  },

  F: {
    corners: [
      Corner.UFL,
      Corner.DLF,
      Corner.ULB,
      Corner.UBR,
      Corner.URF,
      Corner.DFR,
      Corner.DBL,
      Corner.DRB,
    ],
    cornerOri: [1, 2, 0, 0, 2, 1, 0, 0],
    edges: [
      Edge.UR,
      Edge.FL,
      Edge.UL,
      Edge.UB,
      Edge.DR,
      Edge.FR,
      Edge.DL,
      Edge.DB,
      Edge.UF,
      Edge.DF,
      Edge.BL,
      Edge.BR,
    ],
    edgeOri: [0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0],
  },

  B: {
    corners: [
      Corner.URF,
      Corner.UFL,
      Corner.UBR,
      Corner.DRB,
      Corner.DFR,
      Corner.DLF,
      Corner.ULB,
      Corner.DBL,
    ],
    cornerOri: [0, 0, 1, 2, 0, 0, 2, 1],
    edges: [
      Edge.UR,
      Edge.UF,
      Edge.UL,
      Edge.BR,
      Edge.DR,
      Edge.DF,
      Edge.DL,
      Edge.BL,
      Edge.FR,
      Edge.FL,
      Edge.UB,
      Edge.DB,
    ],
    edgeOri: [0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1],
  },
};